# Generated by Django 3.0.4 on 2020-03-25 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='data',
            field=models.DateField(default=datetime.date(2020, 3, 25)),
        ),
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 3, 25, 11, 32, 0, 984181)),
        ),
    ]
