# Generated by Django 3.0.4 on 2020-03-25 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200325_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 3, 25, 12, 4, 23, 169493)),
        ),
    ]
