# Generated by Django 3.0.4 on 2020-03-25 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200325_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 25, 13, 35, 31, 519581, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 3, 25, 13, 35, 31, 519547, tzinfo=utc)),
        ),
    ]
